scripts: mount-flash: make use of mk-flash-layout if present
The mount_ro function was taken from restore-etc.

diff --git a/scripts/mount-flash b/scripts/mount-flash
--- a/scripts/mount-flash
+++ b/scripts/mount-flash
@@ -6,19 +6,45 @@
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 FLASHDIR=/flash
 
-flash="$(cat /proc/cmdline)"
-if [ -n "${flash##*flash=*}" ]; then
-  echo "No flash device specified in /proc/cmdline."
-  exit 1
-fi
-flash=${flash##*flash=}
-flash=${flash%% *}
-[ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
+mount_flash_ro() {
+  local flash
 
-echo "Mounting ${flash} on $FLASHDIR..."
-cd /
-umount -d $FLASHDIR >/dev/null 2>&1
-if ! mount -r $flash $FLASHDIR >/dev/null 2>&1; then
-  echo "Error: mount failed."
-  exit 1
-fi
+  unset FLASH_MBR FLASH_HW FLASH_SW
+
+  if [ -s /var/state/flash-layout.rc ]; then
+    . /var/state/flash-layout.rc
+  fi
+
+  if [ -z "$FLASH_SW" ]; then
+    if [ -x /sbin/mk-flash-layout ]; then
+      /sbin/mk-flash-layout -k && return 0
+      if [ -s /var/state/flash-layout.rc ]; then
+        . /var/state/flash-layout.rc
+      fi
+    fi
+  fi
+
+  if [ -z "$FLASH_SW" ]; then
+    flash="$(cat /proc/cmdline)"
+    if [ -n "${flash##*flash=*}" ]; then
+      echo "No flash device specified in /proc/cmdline."
+      return 1
+    fi
+    flash=${flash##*flash=}
+    flash=${flash%% *}
+    [ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
+  else
+    flash=$FLASH_SW
+  fi
+
+  echo "Mounting ${flash} on $FLASHDIR..."
+  cd /
+  umount -n -d $FLASHDIR >/dev/null 2>&1
+  if ! mount -n -r $flash $FLASHDIR >/dev/null 2>&1; then
+    echo "Error: mount failed."
+    return 1
+  fi
+  return 0
+}
+
+mount_flash_ro
