scripts: make update-boot-image capable of using a pre-mounted directory
Also a few other add-ons such as keeping temp files significant help
troubleshooting boot issues.

diff --git a/scripts/update-boot-image b/scripts/update-boot-image
--- a/scripts/update-boot-image
+++ b/scripts/update-boot-image
@@ -1,12 +1,17 @@
 #!/bin/sh
 
 ## Usage :
-##   $ update-boot-image [-h] [-n] [-q] [-f] [-d $device] $DIR/image.tgz
+##   $ update-boot-image [-k] [-h] [-n] [-q] [-f] [-v] [-m mntdir] [-d device] $DIR/image.tgz
 ##     -h : show this help
 ##     -n : just check the image and do not change anything
 ##     -q : be quiet
 ##     -f : force removal of both old images if required
 ##     -d : use this flash device if not mounted yet
+##     -v : show a valid image version even in quiet mode
+##     -m : use the pre-mounted flash FS <mntdir>
+##     -k : keep the temporary files and output the directory name.
+##   Use -n -q -v to get the image version only.
+##       -n -q -k to extract the image and get access to the files.
 ## 
 ## Return codes :
 ##    0 : everything OK
@@ -30,14 +35,21 @@ FLASH=
 FLASHDIR=/flash
 MOUNTED=
 MOUNTED_RO=
+SHOW_VERSION=
+KEEP_FILES=
 
 while [ $# -gt 0 ]; do
   [ -z "${1##-*}" ] || break
   if [ ".$1" = ".-f" ]; then FORCE=1
   elif [ ".$1" = ".-n" ]; then DRYRUN=1
   elif [ ".$1" = ".-q" ]; then QUIET=1
+  elif [ ".$1" = ".-v" ]; then SHOW_VERSION=1
+  elif [ ".$1" = ".-k" ]; then KEEP_FILES=1
   elif [ ".$1" = ".-d" ]; then
     FLASH="$2"
+    shift
+  elif [ ".$1" = ".-m" ]; then
+    FLASHDIR="$2"
     shift
   else
     if [ ".$1" = ".-h" ]; then
@@ -65,7 +77,9 @@ TEMP="/tmp/temp-$$_$seq"
 do_exit_ok() {
   [ -n "$MOUNTED" ] && \
     ( [ -n "$MOUNTED_RO" ] && mount -ro remount $FLASHDIR || umount $FLASHDIR ) >/dev/null 2>&1
-  [ -n "$TEMP" ] && rm -rf $TEMP >/dev/null 2>&1
+  if [ -n "$TEMP" ]; then
+    [ -z "$KEEP_FILES" ] && rm -rf $TEMP >/dev/null 2>&1 || echo "$TEMP"
+  fi
   exit 0
 }
 
@@ -74,7 +88,9 @@ do_exit_error() {
   err=$1
   [ -n "$MOUNTED" ] && \
     ( [ -n "$MOUNTED_RO" ] && mount -ro remount $FLASHDIR || umount $FLASHDIR ) >/dev/null 2>&1
-  [ -n "$TEMP" ] && rm -rf $TEMP >/dev/null 2>&1
+  if [ -n "$TEMP" ]; then
+    [ -z "$KEEP_FILES" ] && rm -rf $TEMP >/dev/null 2>&1 || echo "$TEMP"
+  fi
   exit ${err:-1}
 }
 
@@ -119,6 +135,12 @@ if ! (cd $TEMP/* ; md5sum -c system.sig >/dev/null 2>&1); then
 fi
 
 [ -z "$QUIET" ] && echo "Valid image."
+
+if [ -n "$SHOW_VERSION" ]; then
+  IMGVER=$(cat $TEMP/*/kernel.ver 2>/dev/null)
+  [ -n "$IMGVER" ] && echo "$IMGVER" || echo "unknown"
+fi
+
 [ "$DRYRUN" = 1 ] && do_exit_ok
 
 if [ -z "$FLASH" ]; then
@@ -166,7 +188,8 @@ if mv $TEMP/* $FLASHDIR/sys/tmp >/dev/null 2>&1; then
     do_exit_error 4
   fi
 else
-  # nothing to remove !
+  # mv failed. The tmp dir might contain incomplete files.
+  rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
   if [ ! -e "$FLASHDIR/sys/active" -a ! -e "$FLASHDIR/sys/backup" ]; then
     rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
     [ -z "$QUIET" ] && echo "Try to reformat flash."
